"""Add filename column to Image model as nullable

Revision ID: 83d93fe78078
Revises: 80ac1047f236
Create Date: 2025-06-18 20:53:59.945922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83d93fe78078'
down_revision = '80ac1047f236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('filename', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('image', schema=None) as batch_op:
        batch_op.drop_column('filename')

    # ### end Alembic commands ###
